2023/04/25 08:08:57 [error] 28#28: *7 directory index of "/html/" is forbidden, client: 192.168.5.1, server: 192.168.5.129, request: "GET / HTTP/1.1", host: "192.168.5.129"
2023/04/25 08:09:01 [error] 28#28: *7 directory index of "/html/" is forbidden, client: 192.168.5.1, server: 192.168.5.129, request: "GET / HTTP/1.1", host: "192.168.5.129"
2023/04/25 08:09:01 [error] 28#28: *7 open() "/html/favicon.ico" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /favicon.ico HTTP/1.1", host: "192.168.5.129", referrer: "http://192.168.5.129/"
2023/04/25 08:13:06 [error] 30#30: *1 open() "/html/login" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /login HTTP/1.1", host: "192.168.5.129"
2023/04/25 08:13:07 [error] 30#30: *1 open() "/html/login" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /login HTTP/1.1", host: "192.168.5.129"
2023/04/25 08:13:18 [error] 30#30: *1 "/html/api/users/login/index.html" is not found (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "POST /api/users/login/ HTTP/1.1", host: "192.168.5.129", referrer: "http://192.168.5.129/login"
2023/04/25 08:35:17 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:35:29 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:35:40 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:35:51 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:36:02 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:36:13 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:36:24 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:36:35 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:36:46 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:36:57 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:37:08 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:37:19 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:37:30 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:37:41 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:37:52 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:38:03 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:23
2023/04/25 08:40:43 [error] 29#29: *1 open() "/html/index" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /index HTTP/1.1", host: "192.168.5.129"
2023/04/25 08:40:57 [error] 29#29: *1 open() "/html/login" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /login HTTP/1.1", host: "192.168.5.129"
2023/04/25 08:41:24 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "POST /api/users/login/ HTTP/1.1", upstream: "http://172.22.0.3:8000/api/users/login/", host: "192.168.5.129", referrer: "http://192.168.5.129/login"
2023/04/25 08:41:34 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "POST /api/users/login/ HTTP/1.1", upstream: "http://172.22.0.3:8000/api/users/login/", host: "192.168.5.129", referrer: "http://192.168.5.129/login"
2023/04/25 08:41:48 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "POST /api/users/login/ HTTP/1.1", upstream: "http://172.22.0.3:8000/api/users/login/", host: "192.168.5.129", referrer: "http://192.168.5.129/login"
2023/04/25 08:42:18 [error] 29#29: *1 open() "/html/login" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /login HTTP/1.1", host: "192.168.5.129"
2023/04/25 08:44:38 [error] 29#29: *4 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "POST /api/users/login/ HTTP/1.1", upstream: "http://172.23.0.3:8000/api/users/login/", host: "192.168.5.129", referrer: "http://192.168.5.129/login"
2023/04/25 17:40:00 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/host/1/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/host/1/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:00 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/challenges/72/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/challenges/72/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:00 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/challenges/comments/?challenge=72&page=1 HTTP/1.1", upstream: "http://172.29.0.3:8000/api/challenges/comments/?challenge=72&page=1", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:00 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/docker/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/docker/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:04 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/host/1/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/host/1/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:04 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/challenges/72/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/challenges/72/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:04 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/challenges/comments/?challenge=72&page=1 HTTP/1.1", upstream: "http://172.29.0.3:8000/api/challenges/comments/?challenge=72&page=1", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:04 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/docker/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/docker/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:40:26 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/challenges/tags/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/challenges/tags/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenges"
2023/04/25 17:40:26 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/challenges/categorys/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/challenges/categorys/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenges"
2023/04/25 17:40:26 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.5.1, server: 192.168.5.129, request: "GET /api/challenges/ HTTP/1.1", upstream: "http://172.29.0.3:8000/api/challenges/", host: "192.168.5.129", referrer: "http://192.168.5.129/challenges"
2023/04/25 17:41:45 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:24
2023/04/25 17:41:57 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:24
2023/04/25 17:42:41 [error] 22#22: *1 open() "/file/attachments/file/attachments/moectf_2022_Locked_bass.zip" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /file/attachments/moectf_2022_Locked_bass.zip HTTP/1.1", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:42:49 [error] 22#22: *4 open() "/file/attachments/file/attachments/moectf_2022_Locked_bass.zip" failed (2: No such file or directory), client: 192.168.5.1, server: 192.168.5.129, request: "GET /file/attachments/moectf_2022_Locked_bass.zip HTTP/1.1", host: "192.168.5.129", referrer: "http://192.168.5.129/challenge/72"
2023/04/25 17:56:14 [error] 28#28: *1 directory index of "/dist/" is forbidden, client: 192.168.5.1, server: 192.168.5.129, request: "GET / HTTP/1.1", host: "192.168.5.129"
2023/04/25 17:56:16 [error] 28#28: *1 directory index of "/dist/" is forbidden, client: 192.168.5.1, server: 192.168.5.129, request: "GET / HTTP/1.1", host: "192.168.5.129"
2023/04/25 17:56:16 [error] 28#28: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 192.168.5.1, server: 192.168.5.129, request: "GET /favicon.ico HTTP/1.1", host: "192.168.5.129", referrer: "http://192.168.5.129/"
2023/04/25 17:56:19 [error] 28#28: *2 directory index of "/dist/" is forbidden, client: 192.168.5.1, server: 192.168.5.129, request: "GET / HTTP/1.1", host: "192.168.5.129"
2023/04/25 17:56:19 [error] 28#28: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 192.168.5.1, server: 192.168.5.129, request: "GET /favicon.ico HTTP/1.1", host: "192.168.5.129", referrer: "http://192.168.5.129/"
